language: python
sudo: required
#this is the configuratiuon for travis the rules and such that it needs to follow

services:
  - docker
 
script:
  - python -m pytest -v
after_success:
  - sh .travis/deploy_dockerhub.sh
